### ISSUE TITLE
cloud caching

### ISSUE THREAD

**Issue by mostafa-tarek10** [snorreks/nx-cloud-functions-deployer#8]
@snorreks 
thanks for the updates ^^

sadly now I have this issue but the deployment working as usual I think it's cloud caching again.

getOptionsFromCode SyntaxError: Expected property name or '}' in JSON at position 3
    at JSON.parse (<anonymous>)
    at wt (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:12:5728)
    at Ue (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:12:4845)
    at async Promise.all (index 2)
    at async qe (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:12:7682)
    at async Promise.all (index 0)
    at async Mt (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:30:3766)
    at async promiseToIterator (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx@17.2.7_@swc-node+register@1.6.8_@swc+core@1.3.101/node_modules/nx/src/command-line/run/run.js:30:11)
    at async getLastValueFromAsyncIterableIterator (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx@17.2.7_@swc-node+register@1.6.8_@swc+core@1.3.101/node_modules/nx/src/utils/async-iterator.js:13:19)
    at async iteratorToProcessStatusCode (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx@17.2.7_@swc-node+register@1.6.8_@swc+core@1.3.101/node_modules/nx/src/command-line/run/run.js:41:29)

**Comment by snorreks** [comment]
It looks like it fails to read the options section of the file. See the [limitation](https://github.com/snorreks/nx-cloud-functions-deployer?tab=readme-ov-file#limitations). When `getOptionsFromCode` fails, it will still deploy. but any options you have added will not be included when deploying.

Can you show me the code after `export default` ?

**Comment by mostafa-tarek10** [comment]
@snorreks 
Seems like my problem is with not providing options at all for all the functions
it was before
export default onWritten<Customer>(handleCustomerWrite);
after I have changed to
export default onWritten<Customer>(handleCustomerWrite, {});
I got the same error

getOptionsFromCode SyntaxError: Expected property name or '}' in JSON at position 3
    at JSON.parse (<anonymous>)
    at wt (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:12:5728)
    at Ue (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:12:4845)
    at async Promise.all (index 2)
    at async qe (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:12:7682)
    at async Promise.all (index 0)
    at async Mt (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx-cloud-functions-deployer@2.5.3_tsx@3.14.0/node_modules/nx-cloud-functions-deployer/executors/deploy/index.js:30:3766)
    at async promiseToIterator (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx@17.2.7_@swc-node+register@1.6.8_@swc+core@1.3.101/node_modules/nx/src/command-line/run/run.js:30:11)
    at async getLastValueFromAsyncIterableIterator (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx@17.2.7_@swc-node+register@1.6.8_@swc+core@1.3.101/node_modules/nx/src/utils/async-iterator.js:13:19)
    at async iteratorToProcessStatusCode (/home/mostafa/Documents/Firebase-NX/node_modules/.pnpm/nx@17.2.7_@swc-node+register@1.6.8_@swc+core@1.3.101/node_modules/nx/src/command-line/run/run.js:41:29)

but at least I knew it looking for fields Expected property name or '}'
I will try to give any options and try

**Comment by mostafa-tarek10** [comment]
still the same error

**Comment by snorreks** [comment]
Weird, can you show me the options section? There might be other limitations not mentioned in the readme

**Comment by mostafa-tarek10** [comment]
> Weird, can you show me the options section? There might be other limitations not mentioned in the readme

I got many functions and I didn't specify any options just the empty object {} for all till now.

**Comment by mostafa-tarek10** [comment]
ok it's the callable functions causing this issue as I tried commenting them out and the error disappeared.

**Comment by mostafa-tarek10** [comment]
fixed.
